# Generated by Django 2.1.1 on 2018-12-20 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20180727_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='latitud',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='longitud',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Estado'),
        ),
    ]
